export const level1 = [
  "Next time it's your turn to talk, start talking for a few seconds while still being muted and then unmute yourself and say 'Sorry I forgot I was muted' ",
  "Step away from the camera for a brief moment",
  "Mute yourself, pretend to sneaze, and then unmute yourself",
  "Unmute yourself just to laugh at the next joke, even if it isn't particularly funny",
  "Mute yourself and pretend to talk to someone offscreen, looking rather annoyed",
  "Nod in agreement though try to do it at a moment when nodding wouldnt normally be your natural reaction",
  "Pretend to swat a fly",
  "Small yawn, cover your mouth",
  "Take a long sip of coffee. If you don't have coffee, get it",
  "Lick your lips, like you got some hot-cheeto powder on them",
  "Turn your back to the camera, just like you turned your back to your childhood friend.",
  "Say 'Oh nice' next time you hear something good",
  "Take a sip of water, but have difficulty swallowing it",
  "If you can change the background, change it to something cheesy like Yosemite or something.",
  "Try to go 30 seconds without blinking. Go!",
  "Is something in your teeth. Look at yourself in the camera and check!",
  "Reference the weather. If its a nice day, say it. This always makes for great conversation.",
  "Your roommate is leaving. Say goodbye to someone offscreen. Seem rather polite.",
  "Smile with teeth. It make the world better, really",
  "Look kinda sad. It's a sad time.",
  "Is something burning? Sniff a little bit, as though you think something might be burning.",
  "It's hot in here. Go open a window.",
  "Unmute yourself, look like you're about to say something, and then don't. Go back to mute.",
  "Look in the camera and brush your hair a bit",
  "Walk around a bit and but carry the camera wwith you. Don't accomplish anything other than walking",
  "Seem optimistim about something",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Nod in agreement though try to do it at a moment when nodding wouldnt normally be your natural reaction",
  "Pretend to swat a fly",
  "Small yawn, cover your mouth",
  "Take a long sip of coffee. If you don't have coffee, get it",
  "Lick your lips, like you got some hot-cheeto powder on them",
  "Turn your back to the camera, just like you turned your back on your childhood friend.",
  "Next time it's your turn to talk, start talking for a few seconds while still being muted and then unmute yourself and say 'Sorry I forgot I was muted' ",
  "Step a way from the camera for a brief moment",
  "Mute yourself, pretend to sneaze, and then unmute yourself",
  "Unmute yourself to say `interesting` to something that wasn't particularly interesting",
  "You haven't been listening! Ask a question about something that has already been answered",
  "Smirk -- a nice big Buttigieg-esque smirk. Really sell it.",
  "Give a compliment to a person in the videoconference that you don't really like",
  "Bob your head a little bit like your listening to a cool song",
  "Address the best looking person on the conference call. Don't be nervous, they obvious like you, too",
  "You agree with someone 100%. Say 'Oh, 100%'. Bonus points if you know what they is a reference to",
  "Yo Adrian! Shadow box a little bit. Everybody is a fighter in this crazy boxing match called life.",
  "Curse accidently and then apologize for it. Bonus points if you're forgiven. Wash out your mouth with soap when this is over.",
  "You are William Wallace, and you give homage to Scottland! Use a termn like 'wee bit', or 'lad', or some other nebulous Scottish slang. ",
  "Who has too thumbs? You do. Give some thumbs up to someone",
  "Spread the love! Next time you talk, say what you love about something.",
  "Analytics, Ernie! Drop some stats like you're Nate Silver",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Its been a long day. Mention how long of a day it has been.",
  "Pass the conversation to someone who has been quite",
  "Say what you think everyone is thinking",
];

export const level2 = [
  "Unmute yourself to say `interesting` to something that wasn't particularly interesting",
  "You haven't been listening! Ask a question about something that has already been answered",
  "Smirk -- a nice big Buttigieg-esque smirk. Really sell it.",
  "Give a compliment to a person in the videoconference that you don't really like",
  "Bob your head a little bit like your listening to a cool song",
  "Address the best looking person on the conference call. Don't be nervous, they obvious like you, too",
  "You agree with someone 100%. Say 'Oh, 100%'. Bonus points if you know what this is a reference to",
  "Mouth `shit` and then give a really panicked look, but calm yourself down before it is addressed.",
  "Nod off for a second and then wake back up, looking startled",
  "Give a very quizzical look, like you have no idea what the hell the person is talking about.",
  "Quickly get up and grab a coffee mug and then come back. Pretend to take a sip and then make a reaction like you burned the holy hell out of your tongue",
  "You haven't been listening! Ask a question about something that has already been answered",
  "Bob your head a little bit like you`re listening to a cool song",
  "Next time you talk, use the phrase 'Having said that' to completely negate what you previously said.",
  "Respond to someone with a comment that is pretty irrelevant",
  "Make a dumb joke. This shouldn't be hard for you.",
  "You are Academy-Award winner Matthew McCanaughey. Say 'Alright, alright, alright' next time you talk",
  "Do some humble-bragging. You deserve some recognition without overtly seeming like a braggart",
  "Next time you`re talking, look offscreen and say goodbye to your roommate, who is leaving",
  "Yurn your camera off and then turn it back on again. Then repeat this in 2 minutes",
  "Say something that sounds sexual but isn't. Prepare to see some smirks from your friends who really need to grow the fuck up",
  "Adjust your camera to a terrible angle. You actually look better this way.",
  "Be cool Honeybunny! Make a subtle reference to a Quintin Tarantino movie that only the coolest bros will get",
  "If you are in a business meeting, take a shot offscreen. If you meeting with family, take a shot onscreen but don't mention that your doing it. Else, take two shots",
  "You're not very observant. Ask, `Is that a new *blank*?` to someone about something that is not new.",
  "Make some friends! Give a compliment to the person who you think probably likes you least.",
  "Who wants to live in a world without Classic Coke? Drop the phrase `You're goddamn right` at some point.",
  "Offer your help to someone",
  "Be in really deep thought about something that someone said. Preferably if someone said something not particularly thought provoking",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
];

export const level3 = [
  "Say something that someone basically just said",
  "Yell 'Mom, meatloaf!'",
  "Make a refernce to something that you hate but don't mention it in the context of you hating it",
  "Start walking around your room for no reason. Bring your laptop/camera with you",
  "Start playing the airdrums. Get really into it but try to keep conversating",
  "Quote a Beatles song",
  "Say something really mean about a friend who is not in the groupchat",
  "Next time you would laugh naturally, laugh hysterically. Be unable to calm down for an embarrassing period of time.",
  "Mute yourself and address someone offscreen, but seem LIVID. Bonus points for mouthing `Just cleanup your shit!` Calm down before it is addressed",
  "Next time you talk, pretend to have the hiccups. Drink water in a weird way to try to cure it.",
  "You haven't been listening! Ask a question about something that has already been answered",
  "Next time you talk, say something that rhymes. You have the option of saying 'Oh, that rhymes' afterward",
  "You do improv! Next time you talk, begin with 'Yes, and'. Extra points if you build off of a joke but make it less funny.",
  "This topic has gone on long enough! Say 'Moving on' to move the conversation forward",
  "Unmute yourself, go to the bathroom and, dont pee, but just flush",
  "Mispronounce someones name. Bonus points if its a common name that you have no business mispronouncing",
  "Say something in iambic pantameter, you goddamn Shakespearean poet. If you can't do it, then go thee to a nunnery, you wench!",
  "Give a backhanded compliment to someone. Speaking of which, you look better than usual today.",
  "You get your news from YouTube. Bring up a current event but get the facts completely wrong.",
  "Next time you talk, use a heavy accent on one word. Try not to be offensive and use an accent that could possibly come from someone of your race",
  "Use the phrase `Let me offer you this`, before offering something that is not particularly insightful",
  "Use the phrase 'I know a lot of people would argue about this' before saying something that no semi-intelligent person would say",
  "You haven't been listening! Ask a question about something that has already been answered",
  "A ghost has entered your room, but you cannot interact with the ghost. But its in your room and you`re fucking terrified, but no one else can know why",
  "Tear up a little bit. It's okay, just let a few tears out. Crying doesnt mean your weak, it means you've been strong for too long",
  "We're back to the Bush administration! Make a reference that is soooooooo 2004.",
  "Mispronounce someones name. Bonus points if its a common name that you have no business mispronouncing",
  "Leave quickly and come back. But when you come back, don't sit in your chair, but squat so it looks like your sitting in a chair. Do this for as long as possible. You're a beast! You got this! Keep going!",
  "Flick someone off offscreen. They probably deserve it.",
  "You are not a partisan hack! Say something that compliments the political party that you least affiliate yourself with. Don't do this sarcasticly. You can also quote a pundit from that political affiliation.",
  "Go offscreen to get something, but dont mute yourself. While offscreen, start barking. People should think its a dog barking, even though its just you. More bonus points if its like a high pitched yelp.",
  "We've been invaded by aliens, and they're disguised as us! You are now an alien who is pretending to be you (and they're doing a good, but not great job)",
  "Talk about a fond memory you have with someone in the group. This memory should be completely fabricated but realistic enough that the other person may think THEY just aren't remembering it.",
  "Next time you begin talking, talk really slowly and quietly, and when someone tries to interupt you hold up a finger and say `let me finish`",
  "Bring up your favorite ex",
  "Bring up someone else's ex",
  "Disagree with someone on something that is very hard to disagree with. Defend this position till your death",
  "Nod your head furiously in agreement to something that you don't agree with",
  "Make a really terrible joke. Be hurt/annoyed when other people don't find it funny",
  "Be super nice but in kind of a corny way",
  "Address the elephant in the room",
  "Offer your help to someone",
  "Give a genuine compliment to the person in the video chat that you've known the longest",
  "React to something in a way that you image one of your parents probably would",
  "Make a comparison thats waaaaaaaaaaaaaaayyyy off",
  "Maybe be quiet for a bit. Gather your thoughts",
  "Next time you get angry or annoyed storm off",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Bob your head a little bit like you`re listening to a cool song",
  "Next time you talk, use the phrase 'Having said that' to completely negate what you previously said.",
  "Respond to someone with a comment that is pretty irrelevant to what they were saying",
  "Make a dumb joke. This shouldn't be hard for you.",
  "You are Academy-Award winner Matthew McCanaughey. Say 'Alright, alright, alright' next time you talk",
  "Do some humble-bragging. You deserve some recognition without overtly seeming like a braggart",
  "Next time your talking, look offscreen and say goodbye to your roommate, who is leaving",
  "Yurn your camera off and then turn it back on again. Then repeat this in 2 minutes",
  "Say something that sounds sexual but isn't. Prepare to see some smirks from your friends who really need to grow the fuck up",
  "Adjust your camera to a terrible angle. You actually look better this way.",
  "Mention Joe Rogan the next time you talk. Use whatever context you want.",
  "Next time you would laugh naturally, laugh hysterically. Be unable to come down for an embarrassing period of time.",
  "Mute yourself and address someone offscreen, but seem LIVID. Bonus points for mouthing `Just cleanup your shit!` Calm down before it is addressed",
  "Next time you talk, pretend to have the hiccups. Drink water in a weird way to try to cure it.",
  "You haven't been listening! Ask a question about something that has already been answered",
  "Next time you talk, say something that rhymes. You have the option of saying 'Oh, that rhymes' afterward",
  "You do improv! Next time you talk, begin with 'Yes, and'. Extra points if you build off of a joke but make it less funny.",
  "This topic has gone on long enough! Say 'Moving on' to move the conversation forward",
  "Unmute yourself, go to the bathroom and, dont pee, but just flush",
  "Mispronounce someones name. Bonus points if its a common name that you have no business mispronouncing",
  "Say something in iambic pantameter, you goddamn Shakespearean poet. If you can't do it, then go thee to a nunnery, you wench!",
  "Give a backhanded compliment to someone. Speaking of which, you look better than usual today.",
  "You get your news from YouTube. Bring up a current event but get the facts completely wrong.",
  "You are Rob Lowe's character from Parks and Rec. Use the word `literally` with emphasis. Bonus points if it's not the classical definition of `literally`.",
  "You've been taken hostage but can't tell anyone explicitly. Say something that sounds normally but your closest friends would know is very much against your core beliefs (To show you're under durress)",
  "Plagiarism! Say something that you didn't come up with (a joke, quote, idea), but make it seem like it's your own.",
  "Life is a comedy for those who think! Say something super pretentious (such as that).",
  "Get offended by something. Preferably something not offensive.",
  "You are Hamlet! Mute yourself and then give a monologue to yourself as if you have to make an important decision",
  "You don`t look like yourself today. Make a facial expression you`ve never made before",
  "Offer your help to someone",
  "Drop the line, `That's very on-brand of you!`",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Ho ho ho! You are Santa Clause",
  "Drainage Eli, draaaaaaaaaaaaaiiiiiiiiiinnnnnnagggggggeeeeee. You are Daniel Plainview, main character of `There Will be Blood`.",
  "You are a Greek God. You always kind of have been :)",
  "You are a fighter-pilot in the middle of a dogfight!",
  "You are the unintelligent side-character from a Shakespeare comedy.",
  "You are a mediocre singer-songwriter in the middle of the slow part of the song",
  "You are the king of a great empire but have a very noticable inferiority complex",
  "You are a philosophy professor",
  "You are a person whose personality traits are a mix of those of the tallest and shortest person on the conference call",
  "You are someone who hasn`t slept in a week",
  "You are your favorite Marvel character. Bonus points if it's Thor, as it should be",
  "Ho ho ho! You are Santa Clause",
  "You are a President of the United States, who served between 1800-1900. Pick one in particular. Bonus points if it isn't Lincoln.",
  "You have telekenisis, but you don't want anyone to know. But you still can't fight off the urge to explore your own powers.",
  "You are someone whose been living under a rock for the past 10 years. You can interpret this literally or figuratively",
  "You are Petyr Baelish. Everyone on the call is your enemy. Everyone on the call is your friend.",
  "You are an idiot-savant. Your choice as to what you're good at.",
  "You are a carpenter. A real salt-of-the-Earth man",
  "You are lost, and are in the wrong group chat.",
  "You're a hipster",
  "You're a wizard, Harry",
  "You are yourself from 10 years ago.",
  "You are a sportscaster",
  "You are a feminist",
  "You are an alien who is pretending to be you",
  "You are obsessed with your high school glory days",
  "You are a DJ in the middle of an EDM set",
  "You are Joe Exotic",
  "You are incredibly arrogant but are trying your best to seem modest.",
  "You are Troy Bolton. You're heads in the game but you're hearts in the song.",
  "You are a knight who has just slayed a dragon and saved a princess, but upon turning home the princess has immediately gone back to their ex and all the commoners are claiming that the dragon was overhyped to begin with",
  "You are the person who is speaking right NOW",
  "You are yourself from 10 years in the future",
  "You are the wingman/hypeman/side-kick of another person in the chat. Pick whoever",
  "You are a slam-poet",
  "You are the therapist of the person talking right now",
  "You are a presidential candidate who has been campaigning so long that they cannot stop talking as if they are in the middle of a stump speech",
  "You are controlled by two people with remote controls, but now they're fighting over what to do with you",
  "You are a school-teacher",
  "You are a youth-pastor",
  "You are an Instagram influencer",
  "You enjoy three things: Bears. Beets. Battlestar Galactica",
  "You are the mediocre lead-singer of a struggling emo-pop band",
  "You are a monk",
  "You are your favorite prompt of whatever you've had before. If this is your first prompt, just be yourself",
  "You are your sibling. If you are an only child, just be yourself",
  "You write for Pitchfork",
  "You are a ghost",
  "You are in love with the person talking",
  "You are a statue that has just recently come to life",
  "You are your favorite high school teacher",
  "Grab some water",
  "You are Dave Chappelle's Tyrone Biggums character from The Chappelle Show. He was a crackhead.",
  "You are Elon Musk",
  "You are speed-dating, and you have a speed-date with everyone in the chatroom",
  "You and the tallest person in the chat are planning to kill the shortest person in the chat",
  "You are a Tom Hardy character. Pick your favorite",
  "You've just become aware of your own mortality for the first time",
  "You are a genie",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
];

//Politics
export const Politics = [
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Someone is making a good point. Nod in agreement",
  "You're about to make a good point, but you forgot what you were going to say. Start talking and then say either `I forgot what I was going to say` or `I don't know where I was going with that`",
  "Make a comparison to Nazi Germany",
  "Make a comparison to Soviet Russia",
  "Make a comparison to Castro's Cuba",
  "Mention something that could've been said by Andrew Yang",
  "Namedrop someone who you think may be President in the future, excluding Trump and Biden",
  "Someone is making a great point. Nod FURIOUSLY in agreement",
  "Someone is making a TERRIBLE point. Nod furiously in disagreement",
  "Ask a question to someone who has been quite",
  "Next time someone gets cut off, say 'Hey, let them finish their thought'",
  "You are a President in the 1800s",
  "Say what you would do if you were president",
  "'How are we going to pay for it?' Say something that Amy Klobuchar might say",
  "You are a comedian who is doing the same dry anti-SJW shit. Complain about hyper-sensitivity in comedy or America",
  "You are one of the dumbass hosts of Pod Save America. Say something factually incorrect and say it in a really smug way, and then laugh at your own unfunny observation",
  "Say 'going back to what you said earlier' and then mention what someone said earlier",
  "Go to the bathroom",
  `Mention one of the Lesson We Learned™ from 2016`,
  "Mention one of the accomplishments of the Obama administration",
  "Mention one of the failings of the Obama administration",
  "Grab some water and take a sip",
  "Nod in agreement though try to do it at a moment when nodding wouldnt normally be your natural reaction",
  "Pretend to swat a fly",
  "Small yawn, cover your mouth",
  "Take a long sip of coffee. If you don't have coffee, get it",
  "Mention the #MeToo Movement and its effects on our political landscape",
  "You don't know what to make of someone's opinion and you feel the need to vocalize that. Say something along the lines of 'Not sure how I feel about that one'.",
  "Next time someone makes a point, nod and slow clap.",
  "Next time someone mentions the a Scandanavian country, mention how Sweden has a Neo-Nazi problem",
  "Say `I know this is an unpopular opinion` followed by something that is in no way an unpopular opinion",
  "You can see things both ways. Straddle the fence on whatever issue is being discussed",
  "Grab some water",
  "Say `moving on` to move the conversation along",
  "Next time someone says anything mildly interesting, say how you heard about that on a podcast",
  "Drop the line `Facts dont care about your feelings` before/after owning someone with facts and/or logic",
  "Maybe sit on the sidelines of this argument",
  "Next time someone is making a point, unmute yourself, lean into the mic and say `Wrong`, and then unmute yourself",
  "Get offended by something. Preferably something not offensive.",
  "Bring up the founding fathers. Bonus points if you suggest what they would have wanted",
  "Next time you get angry or annoyed storm off",
  "Give a genuine compliment to the person in the video chat that you've known the longest",
  "React to something in a way that you image one of your parents probably would",
  "Make a comparison thats waaaaaaaaaaaaaaayyyy off",
  "Maybe be quiet for a bit. Gather your thoughts",
];
//All character-based
export const Character = [
  "Ho ho ho! You are Santa Clause",
  "Drainage Eli, draaaaaaaaaaaaaiiiiiiiiiinnnnnnagggggggeeeeee. You are Daniel Plainview, main character of `There Will be Blood`.",
  "You are a Greek God. You always kind of have been :)",
  "You are a fighter-pilot in the middle of a dogfight!",
  "You are the unintelligent side-character from a Shakespeare comedy.",
  "You are a mediocre singer-songwriter in the middle of the slow part of the song",
  "You are the king of a great empire but have a very noticable inferiority complex",
  "You are a philosophy professor",
  "You are a person whose personality traits are a mix of those of the tallest and shortest person on the conference call",
  "You are someone who hasn`t slept in a week",
  "You are your favorite Marvel character. Bonus points if it's Thor, as it should be",
  "Ho ho ho! You are Santa Clause",
  "You are a President of the United States, who served between 1800-1900. Pick one in particular. Bonus points if it isn't Lincoln.",
  "You have telekenisis, but you don't want anyone to know. But you still can't fight off the urge to explore your own powers.",
  "You are someone whose been living under a rock for the past 10 years. You can interpret this literally or figuratively",
  "You are Petyr Baelish. Everyone on the call is your enemy. Everyone on the call is your friend.",
  "You are an idiot-savant. Your choice as to what you're good at.",
  "You are a carpenter. A real salt-of-the-Earth man",
  "You are lost, and are in the wrong group chat.",
  "You're a hipster",
  "You're a wizard, Harry",
  "You are yourself from 10 years ago.",
  "You are a sportscaster",
  "You are a feminist",
  "You are an alien who is pretending to be you",
  "You are obsessed with your high school glory days",
  "You are a DJ in the middle of an EDM set",
  "You are Joe Exotic",
  "You are incredibly arrogant but are trying your best to seem modest.",
  "You are Troy Bolton. You're heads in the game but you're hearts in the song.",
  "You are a knight who has just slayed a dragon and saved a princess, but upon turning home the princess has immediately gone back to their ex and all the commoners are claiming that the dragon was overhyped to begin with",
  "You are the person who is speaking right NOW",
  "You are yourself from 10 years in the future",
  "You are the wingman/hypeman/side-kick of another person in the chat. Pick whoever",
  "You are a slam-poet",
  "You are the therapist of the person talking right now",
  "You are a presidential candidate who has been campaigning so long that they cannot stop talking as if they are in the middle of a stump speech",
  "You are controlled by two people with remote controls, but now they're fighting over what to do with you",
  "You are a school-teacher",
  "You are a youth-pastor",
  "You are an Instagram influencer",
  "You enjoy three things: Bears. Beets. Battlestar Galactica",
  "You are the mediocre lead-singer of a struggling emo-pop band",
  "You are a monk",
  "You are your favorite prompt of whatever you've had before. If this is your first prompt, just be yourself",
  "You are your sibling. If you are an only child, just be yourself",
  "You write for Pitchfork",
  "You are a ghost",
  "You are in love with the person talking",
  "You are a statue that has just recently come to life",
  "You are your favorite high school teacher",
  "Grab some water",
  "You are Dave Chappelle's Tyrone Biggums character from The Chappelle Show. He was a crackhead.",
  "You are Elon Musk",
  "You are speed-dating, and you have a speed-date with everyone in the chatroom",
  "You and the tallest person in the chat are planning to kill the shortest person in the chat",
  "You are a Tom Hardy character. Pick your favorite",
  "You've just become aware of your own mortality for the first time",
  "You are a genie",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
  "Just be yourself. That's good enough for me :)",
];
