export const level1 = [
  "Next time it's your turn to talk, start talking for a few seconds while still being muted and then unmute yourself and say 'Sorry I forgot I was muted' ",
  "Step away from the camera for a brief moment",
  "Use the term 'circling back to' or some other bit of business jargon",
  "Say something that is out of character for you",
  "Nod your head furiously in agreement to something that you don't agree with",
  "Mute yourself, pretend to sneeze, and then unmute yourself",
  "Leave back into your chair until it starts to tip over and then reposition it",
  "Unmute yourself just to laugh at the next joke, even if it isn't particularly funny",
  "Mute yourself and pretend to talk to someone offscreen, looking rather annoyed",
  "Nod in agreement though try to do it at a moment when nodding wouldn’t normally be your natural reaction",
  "Pretend to swat a fly",
  "Next time you agree with something say 'Yeah, no, definitely'",
  "Try to make the same face that you are making on your driver's license",
  "Small yawn, cover your mouth",
  "Take a long sip of coffee. If you don't have coffee, get it",
  "Use the term, 'In a perfect world'",
  "Say something that you imagine a super charasmatic person might say",
  "Lick your lips, like you got some hot-cheeto powder on them",
  "Turn your back to the camera, just like you turned your back to your childhood friend.",
  "Say 'Oh nice' next time you hear something good",
  "Take a sip of water, but have difficulty swallowing it",
  "Say something that you imagine a good-hearted but socially awkward dork might say",
  "If you can change the background, change it to something cheesy like Yosemite or something.",
  "Try to go 30 seconds without blinking. Go!",
  "Is something in your teeth? Look at yourself in the camera and check!",
  "Reference the weather. If it's a nice day, say it. This always makes for great conversation.",
  "Your roommate is leaving. Say goodbye to someone offscreen. Seem rather polite.",
  "Smile with teeth. It make the world better, really",
  "Look kinda sad. It's a sad time.",
  "Is something burning? Sniff a little bit, as though you think something might be burning.",
  "It's hot in here. Go open a window.",
  "Unmute yourself, look like you're about to say something, and then don't. Go back to mute.",
  "Look in the camera and brush your hair a bit",
  "Walk around a bit and carry the camera with you. Don't accomplish anything other than walking",
  "Seem optimistic about something",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Nod in agreement though try to do it at a moment when nodding wouldn’t normally be your natural reaction",
  "Pretend to swat a fly",
  "Small yawn, cover your mouth",
  "Next time you agree with something say 'Yeah, no, definitely'",
  "Say something kind of sarcastic",
  "Bob your head a little bit like you`re listening to a cool song",
  "Take a long sip of coffee. If you don't have coffee, get it",
  "Lick your lips, like you got some hot-cheeto powder on them",
  "Turn your back to the camera, just like you turned your back on your childhood friend.",
  "Next time it's your turn to talk, start talking for a few seconds while still being muted and then unmute yourself and say 'Sorry I forgot I was muted' ",
  "Step away from the camera for a brief moment",
  "Mute yourself, pretend to sneeze, and then unmute yourself",
  "Unmute yourself to say `interesting` to something that wasn't particularly interesting",
  "You haven't been listening! Ask a question about something that has already been answered",
  "Smirk -- a nice big Buttigieg-esque smirk. Really sell it.",
  "Give a compliment to a person in the videoconference that you don't really like",
  "Bob your head a little bit like your listening to a cool song",
  "Address the best looking person on the conference call. Don't be nervous, they obvious like you, too",
  "You agree with someone 100%. Say 'Oh, 100%'. Bonus points if you know what they is a reference to",
  "Yo Adrian! Shadow box a little bit. Everybody is a fighter in this crazy boxing match called life.",
  "Curse accidentally and then apologize for it. Bonus points if you're forgiven. Wash out your mouth with soap when this is over.",
  "You are William Wallace, and you give homage to Scotland! Use a term like 'wee bit', or 'lad', or some other nebulous Scottish slang. ",
  "Who has two thumbs? You do. Give some thumbs up to someone",
  "Spread the love! Next time you talk, say what you love about something.",
  "Say 'oh, don't get me started on that' next time something is mentioned that you have very little interest in talking about",
  "Analytics, Ernie! Drop some stats like you're Nate Silver",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "It’s been a long day. Mention how long of a day it has been.",
  "Pass the conversation to someone who has been quite",
  "Say what you think everyone is thinking",
  "Next time someone asks a question say 'That's a good question'",
  "Shake your head back and forth and look upward as if you're really considering what the last person said",
];

export const level2 = [
  "Shake your head back and forth and look upward as if you're really considering what the last person said",
  "Unmute yourself to say `interesting` to something that wasn't particularly interesting",
  "You haven't been listening! Ask a question about something that has already been answered",
  "Try to make the same face that you are making on your driver's license",
  "Smirk -- a nice big Buttigieg-esque smirk. Really sell it.",
  "Give a compliment to a person in the videoconference that you don't really like",
  "Mention a frustration your having with modern technology",
  "Bob your head a little bit like your listening to a cool song",
  "Use the term 'circling back to' or some other bit of business jargon",
  "Say something that is out of character for you",
  "Next time you talk, talk a little louder than you should",
  "Address the best looking person on the conference call. Don't be nervous, they obvious like you, too",
  "Nod your head furiously in agreement to something that you don't agree with",
  "Refer to something as the 'greatest of all time'",
  "You agree with someone 100%. Say 'Oh, 100%'.",
  "Mouth `shit` and then give a really panicked look, but calm yourself down before it is addressed.",
  "Nod off for a second and then wake back up, looking startled",
  "Give a very quizzical look, like you have no idea what the hell the person is talking about.",
  "Quickly get up and grab a coffee mug and then come back. Pretend to take a sip and then make a reaction like you burned the holy hell out of your tongue",
  "Next time someone asks a question say 'That's a good question'",
  "Next time you agree with something say 'Yeah, no, definitely'",
  "Say something kind of sarcastic",
  "Bob your head a little bit like you`re listening to a cool song",

  "Respond to someone with a comment that is pretty irrelevant",
  "Make a dumb joke. This shouldn't be hard for you.",
  "You are Academy-Award winner Matthew McCanaughey. Say 'Alright, alright, alright' next time you talk",
  "Do some humble-bragging. You deserve some recognition without overtly seeming like a braggart",
  "Next time you're talking, look offscreen and say goodbye to your roommate, who is leaving",
  "Turn your camera off and then turn it back on again. Then repeat this in 2 minutes",
  "Say something that sounds sexual but isn't. Prepare to see some smirks from your friends who really need to grow the fuck up",
  "Adjust your camera to a terrible angle. You actually look better this way.",
  "Be cool, Honeybunny! Make a subtle reference to a Quintin Tarantino movie that only the coolest bros will get",
  "You're not very observant. Ask, `Is that a new *blank*?` to someone about something that is not new.",
  "Make some friends! Give a compliment to the person who you think probably likes you least.",
  "Who wants to live in a world without Classic Coke? Drop the phrase 'You`re goddamn right' at some point.",
  "Offer your help to someone",
  "Be in really deep thought about something that someone said. Preferably if someone said something not particularly thought provoking",
  "Turn around as if alarmed, and then say ‘hm… I must be hearing things’",
  "Scratch your head for 20 seconds straight",
  "Make that face that Tucker Carlson makes all the time. You know the one",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Start eating something",
  "Say ‘I’m going to the bathroom, I’ll be back in a couple minutes’ and return in less than 20 seconds",
  "Say 'oh, don't get me started on that' next time something is mentioned that you have very little interest in talking about",
];

export const level3 = [
  "Say something that someone basically just said",
  "Tell a short but boring and irrelevant story",
  "Grab some water",
  "Yell 'Mom, meatloaf!'",
  "Make a reference to something that you hate but don't mention it in the context of you hating it",
  "Start walking around your room for no reason. Bring your laptop/camera with you",
  "Start playing the air drums. Get really into it but try to keep conversating",
  "Quote a Beatles song",
  "Someone in this video-chat has betrayed you. Try to find out who it is, and in what way you’ve been betrayed",
  "Utter a sentence that you’ve never said before and, God willing, will never say again",
  "Say something that could be a lyric in a Billie Eilish song",
  "Quote a line from 'Game of Thrones'",
  "Mute yourself and start eating, but chew like a cow",
  "Next time someone says something funny say 'Haha, you should tweet that'",
  "Do a really obnoxious 'Psssssssssssshhhhhhhhhhhhhhhh, no!', next time someone says something innocuous",
  "Next time someone says something funny say 'That could be standup!'",
  "Nod furiously to something you don’t agree with",
  "Shake your head at something that you absolutely agree with",
  "Say 'One of the best pieces of advice I've ever heard was ...' followed by advice that is bad. Not like, absurdly bad, just slightly but genuinely bad.",
  "Say something really mean about a friend who is not in the video-chat",
  "Say 'I have to say, I really love talking to y'all and I'm glad we did this' or something like that. Bonus points if it isn't true.",
  "Next time you would laugh naturally, laugh hysterically. Be unable to calm down for an embarrassing period of time.",
  "Mute yourself and address someone offscreen, but seem LIVID. Bonus points for mouthing `Just cleanup your shit!` Calm down before it is addressed",
  "Next time you talk, pretend to have the hiccups. Drink water in a weird way to try to cure it.",
  "You haven't been listening! Ask a question about something that has already been answered",
  "Next time you talk, say something that rhymes. You have the option of saying 'Oh, that rhymes' afterward",
  "You do improv! Next time you talk, begin with 'Yes, and'. Extra points if you build off of a joke but make it less funny.",
  "This topic has gone on long enough! Say 'Moving on' to move the conversation forward",
  "Unmute yourself, go to the bathroom and, don't pee, but just flush",
  "Mispronounce someone's name. Bonus points if its a common name that you have no business mispronouncing",
  "Dance a bit. Not a lot. Just a bit.",
  "Say something Shakespearean. If you can't do it, then go thee to a nunnery, you wench!",
  "Give a backhanded compliment to someone. Speaking of which, you look better than usual today.",
  "You get your news from YouTube. Bring up a current event but get the facts completely wrong.",
  "Next time you talk, use a heavy accent on one word. Try not to be offensive and use an accent that could possibly come from someone of your race",
  "Use the phrase `Let me offer you this`, before offering something that is not particularly insightful",
  "Use the phrase 'I know a lot of people would argue about this' before saying something that no semi-intelligent person would say",
  "You haven't been listening! Ask a question about something that has already been answered",
  "A ghost has entered your room, but you cannot interact with the ghost. But its in your room and you`re fucking terrified, but no one else can know why",
  "Tear up a little bit. It's okay, just let a few tears out. Crying doesn't mean you’re weak, it means you've been strong for too long",
  "We're back to the Bush administration! Make a reference that is soooooooo 2004.",
  "Mispronounce someone's name. Bonus points if its a common name that you have no business mispronouncing",
  "Leave quickly and come back. But when you come back, don't sit in your chair, but squat so it looks like you're sitting in a chair. Do this for as long as possible. You're a beast! You got this! Keep going!",
  "Flick someone off offscreen. They probably deserve it.",
  "You are not a partisan hack! Say something that compliments the political party that you least affiliate yourself with. Don't do this sarcastically. You can also quote a pundit from that political affiliation.",
  "Go offscreen to get something, but don't mute yourself. While offscreen, start barking. People should think it's a dog barking, even though it's just you. More bonus points if it's like a high pitched yelp.",
  "We've been invaded by aliens, and they're disguised as us! You are now an alien who is pretending to be you (and they're doing a good, but not great job)",
  "Talk about a fond memory you have with someone in the group. This memory should be completely fabricated but realistic enough that the other person may think THEY just aren't remembering it.",
  "Next time you begin talking, talk really slowly and quietly, and when someone tries to interrupt you hold up a finger and say `let me finish`",
  "Bring up your favorite ex",
  "Bring up someone else's ex",
  "Disagree with someone on something that is very hard to disagree with. Defend this position till your death",
  "Nod your head furiously in agreement to something that you don't agree with",
  "Make a really terrible joke. Be hurt/annoyed when other people don't find it funny",
  "Be super nice but in kind of a corny way",
  "Address the elephant in the room",
  "Offer your help to someone",
  "Give a genuine compliment to the person in the video chat that you've known the longest",
  "React to something in a way that you imagine one of your parents probably would",
  "Make a comparison that's waaaaaaaaaaaaaaayyyy off",
  "Take a joke or idea from someone else in the videochat and say it without citing your sources",
  "Maybe be quiet for a bit. Gather your thoughts",
  "Next time you get angry or annoyed storm off",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Bob your head a little bit like you`re listening to a cool song",

  "Respond to someone with a comment that is pretty irrelevant to what they were saying",
  "Make a dumb joke. This shouldn't be hard for you.",
  "You are Academy-Award winner Matthew McCanaughey. Say 'Alright, alright, alright' next time you talk",
  "Do some humble-bragging. You deserve some recognition without overtly seeming like a braggart",
  "Next time your talking, look offscreen and say goodbye to your roommate, who is leaving",
  "Turn your camera off and then turn it back on again. Then repeat this in 2 minutes",
  "Say something that sounds sexual but isn't. Prepare to see some smirks from your friends who really need to grow the fuck up",
  "Adjust your camera to a terrible angle. You actually look better this way.",
  "Mention Joe Rogan the next time you talk. Use whatever context you want.",
  "Next time you would laugh naturally, laugh hysterically. Be unable to come down for an embarrassing period of time.",
  "Mute yourself and address someone offscreen, but seem LIVID. Bonus points for mouthing `Just cleanup your shit!` Calm down before it is addressed",
  "Next time you talk, pretend to have the hiccups. Drink water in a weird way to try to cure it.",
  "You haven't been listening! Ask a question about something that has already been answered",
  "Next time you talk, say something that rhymes. You have the option of saying 'Oh, that rhymes' afterward",
  "You do improv! Next time you talk, begin with 'Yes, and'. Extra points if you build off of a joke but make it less funny.",
  "This topic has gone on long enough! Say 'Moving on' to move the conversation forward",
  "Unmute yourself, go to the bathroom and, don't pee, but just flush",
  "Mispronounce someone's name. Bonus points if its a common name that you have no business mispronouncing",
  "Say something in iambic pentameter, you goddamn Shakespearean poet. If you can't do it, then go thee to a nunnery, you wench!",
  "Give a backhanded compliment to someone. Speaking of which, you look better than usual today.",
  "You get your news from YouTube. Bring up a current event but get the facts completely wrong.",
  "You are Rob Lowe's character from Parks and Rec. Use the word `literally` with emphasis. Bonus points if it's not the classical definition of `literally`.",

  "Plagiarism! Say something that you didn't come up with (a joke, quote, idea), but make it seem like it's your own.",
  "Life is a comedy for those who think! Say something super pretentious (such as that).",
  "Get offended by something. Preferably something not offensive.",
  "You are Hamlet! Mute yourself and then give a monologue to yourself as if you have to make an important decision",
  "You don`t look like yourself today. Make a facial expression you`ve never made before",
  "Offer your help to someone",
  "Make up a name for a fake musician, and when you mention them, act really shocked that no one knows who that is",
  "Start putting on more layers without explanation",
  "Respond to something someone says with ‘sounds like my ex-wife’",
  "Say ‘I like the new look’ to someone whose appearance hasn’t changed recently",
  "Start eating something",
  "Say ‘I’m going to the bathroom, I’ll be back in a couple minutes’ and return in less than 20 seconds",
  "Act suddenly concerned toward a specific person, and ask them if they’re okay",
  "Drop the line, `That's very on-brand of you!`",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Ho ho ho! You are Santa Clause",
  "Drainage Eli, draaaaaaaaaaaaaiiiiiiiiiinnnnnnagggggggeeeeee. You are Daniel Plainview, main character of `There Will be Blood`.",
  "You are a Greek God. You always kind of have been :)",
  "You are a fighter-pilot in the middle of a dogfight!",
  "You are the unintelligent side-character from a Shakespeare comedy.",
  "You are a mediocre singer-songwriter in the middle of the slow part of the song",
  "You are the king of a great empire but have a very noticeable inferiority complex",
  "You are a philosophy professor",
  "You are a person whose personality traits are a mix of those of the tallest and shortest person on the conference call",
  "You are someone who hasn't slept in a week",
  "You are your favorite Marvel character. Bonus points if it's Thor, as it should be",
  "Ho ho ho! You are Santa Clause",
  "You are a President of the United States, who served between 1800-1900. Pick one in particular. Bonus points if it isn't Lincoln.",
  "You have telekinesis, but you don't want anyone to know. But you still can't fight off the urge to explore your own powers.",
  "You are someone who's been living under a rock for the past 10 years. You can interpret this literally or figuratively",
  "You are Petyr Baelish. Everyone on the call is your enemy. Everyone on the call is your friend.",
  "You are an idiot-savant. Your choice as to what you're good at.",
  "You are a carpenter. A real salt-of-the-Earth man",
  "You are lost, and are in the wrong group chat.",
  "You're a hipster",
  "You're a wizard, Harry",
  "You are yourself from 10 years ago.",
  "You are a sportscaster",
  "You are a feminist",
  "You are an alien who is pretending to be you",
  "You are obsessed with your high school glory days",
  "You are a DJ in the middle of an EDM set",
  "You are Joe Exotic",
  "You are incredibly arrogant but are trying your best to seem modest.",
  "You are Troy Bolton. You're heads in the game but you're hearts in the song.",
  "You are a knight who has just slayed a dragon and saved a princess, but upon turning home the princess has immediately gone back to their ex and all the commoners are claiming that the dragon was overhyped to begin with",
  "You are the person who is speaking right NOW",
  "You are yourself from 10 years in the future",
  "You are the wingman/hypeman/side-kick of another person in the chat. Pick whoever",
  "You are a slam-poet",
  "You are the therapist of the person talking right now",
  "You are a presidential candidate who has been campaigning so long that they cannot stop talking as if they are in the middle of a stump speech",
  "You are controlled by two people with remote controls, but now they're fighting over what to do with you",
  "You are a school-teacher",
  "You are a youth-pastor",
  "You are an Instagram influencer",
  "You enjoy three things: Bears. Beets. Battlestar Galactica",
  "You are the mediocre lead-singer of a struggling emo-pop band",
  "You are your favorite prompt of whatever you've had before. If this is your first prompt, just be yourself",
  "You are your sibling. If you are an only child, just be yourself",
  "You write for Pitchfork",
  "You are a ghost",
  "You are in love with the person talking",
  "You are a statue that has just recently come to life",
  "You are your favorite high school teacher",
  "Grab some water",
  "You are Dave Chappelle's Tyrone Biggums character from The Chappelle Show. He was a crackhead.",
  "You are Elon Musk",
  "You are speed-dating, and you have a speed-date with everyone in the chatroom",
  "You and the tallest person in the chat are planning to kill the shortest person in the chat",
  "You are a Tom Hardy character. Pick your favorite. Bonus points if it's Alfie Solomons.",
  "You've just become aware of your own mortality for the first time",
  "You are a genie",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
];

//Politics
export const Politics = [
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Someone is making a good point. Nod in agreement",
  "You're about to make a good point, but you forgot what you were going to say. Start talking and then say either `I forgot what I was going to say` or `I don't know where I was going with that`",
  "Mention how the vice-presidency is basically a ceremonial position",
  "Refer to Washington, DC as 'The Swamp'",
  "Start emphatically pointing at the camera when someone is making a good point",
  "Make a comparison to Soviet Russia",
  "Make a comparison to Castro's Cuba",
  "Say something that could've been said by Andrew Yang",
  "Namedrop someone who you think may be President in the future, excluding Trump and Biden",
  "Someone is making a great point. Nod FURIOUSLY in agreement",
  "Someone is making a TERRIBLE point. Nod furiously in disagreement",
  "Ask a question to someone who has been quiet",
  "Next time someone gets cut off, say 'Hey, let them finish their thought'",
  "You are a President in the 1800s",
  "Say what you would do if you were president",
  "'How are we going to pay for it?' Say something that Amy Klobuchar might say",
  "You are a comedian who is doing the same dry anti-SJW shit. Complain about hyper-sensitivity in comedy or America",
  "You are one of the dumbass hosts of Pod Save America. Say something factually incorrect and say it in a really smug way, and then laugh at your own unfunny observation",
  "In a Joe Biden-esque fashion, say ‘look, the fact is…’ or address someone as ‘Jack’",
  "Pull a Kamala Harris and tell a story that dramatically ends in ‘that little girl was ME’",
  "Wave your hands around while you talk, the way Bernie Sanders does",
  "Mention trickle-down economics",
  "Say something vague about ‘shifting the narrative’ and ‘asking the right questions’",
  "Say ‘I see where you’re coming from, but’",
  "Make that face that Tucker Carlson makes all the time. You know the one",
  "Say 'going back to what you said earlier' and then mention what someone said earlier",
  "Go to the bathroom",
  "Mention one of the Lessons We Learned™ from 2016",
  "Mention one of the accomplishments of the Obama administration",
  "Mention one of the failings of the Obama administration",
  "You are a debate moderator who continues to be steamrolled by the candidates",
  "You the phrase 'Americans have trouble talking about ...' and complete it with something that Americans talk about all the time",
  "Grab some water and take a sip",
  "Nod in agreement though try to do it at a moment when nodding wouldn’t normally be your natural reaction",
  "Pretend to swat a fly",
  "Small yawn, cover your mouth",
  "Take a long sip of coffee. If you don't have coffee, get it",
  "Mention the #MeToo Movement and its effects on our political landscape",
  "You don't know what to make of someone's opinion and you feel the need to vocalize that. Say something along the lines of 'Not sure how I feel about that one'.",
  "Next time someone makes a point, nod and slow clap.",
  "Next time someone mentions the a Scandanavian country, mention how Sweden has a Neo-Nazi problem",
  "Say `I know this is an unpopular opinion` followed by something that is in no way an unpopular opinion",
  "You can see things both ways. Straddle the fence on whatever issue is being discussed",
  "Grab some water",
  "Say ‘That simply isn’t true’ next time someone says something that is true",
  "Your Presidential Portrait will be whatever is on the video of you in five seconds. Pose for your portrait in FIVE, FOUR, THREE, TWO, ONE!",
  "Say `moving on` to move the conversation along",
  "Next time someone says anything mildly interesting, say how you heard about that on a podcast",
  "Drop the line ‘Facts don't care about your feelings’ before/after owning someone with facts and/or logic",
  "Maybe sit on the sidelines of this argument",
  "Next time someone is making a point, unmute yourself, lean into the mic and say `Wrong`, and then unmute yourself",
  "Say something insulting about Time Magazine’s reigning Person of the Year™ Greta Thunberg",
  "Get offended by something. Preferably something not offensive.",
  "Bring up the founding fathers. Bonus points if you suggest what they would have wanted",
  "Next time you get angry or annoyed storm off",
  "Give a genuine compliment to the person in the video chat that you've known the longest",
  "React to something in a way that you imagine one of your parents probably would",
  "Make a comparison that's waaaaaaaaaaaaaaayyyy off",
  "Maybe be quiet for a bit. Gather your thoughts",
  "You are Rachel Maddow",
  "You are your pet if your pet was a human",
  "You have the personality and mannerisms of Alex Jones but the worldview of Mother Theresa or some other saintly figure",
];
//All character-based
export const Character = [
  "You are your pet if your pet was a person",
  "Ho ho ho! You are Santa Clause",
  "Drainage Eli, draaaaaaaaaaaaaiiiiiiiiiinnnnnnagggggggeeeeee. You are Daniel Plainview, main character of ‘There Will be Blood’.",
  "You are a Greek God. You always kind of have been :)",
  "You are Ellen DeGenerous, but not the one you see on TV, the one you hear all the terrible stories about",
  "You are a fighter-pilot in the middle of a dogfight!",
  "You are the unintelligent side-character from a Shakespeare comedy.",
  "You are a mediocre singer-songwriter in the middle of the slow part of the song",
  "You are the king of a great empire but have a very noticeable inferiority complex",
  "You are a philosophy professor",
  "You are a person whose personality traits are a mix of those of the tallest and shortest person on the conference call",
  "You are someone who hasn't slept in a week",
  "You are motivational speaker Tony Robbins",
  "You are your favorite Marvel character. Bonus points if it's Thor, as it should be",
  "Ho ho ho! You are Santa Clause",
  "You have the personality and mannerisms of Alex Jones but the worldview of Mother Theresa or some other saintly figure",
  "You are a President of the United States, who served between 1800-1900. Pick one in particular. Bonus points if it isn't Lincoln.",
  "You have telekinesis, but you don't want anyone to know. But you still can't fight off the urge to explore your own powers.",
  "You are someone who's been living under a rock for the past 10 years. You can interpret this literally or figuratively",
  "You are Petyr Baelish. Everyone on the call is your enemy. Everyone on the call is your friend.",
  "You are an idiot-savant. Your choice as to what you're good at.",
  "You are a carpenter. A real salt-of-the-Earth man",
  "You are lost, and are in the wrong group chat.",
  "You are Joe Goldberg, main character of Netflix's 'You'",
  "Bring up something from the last news article you read",
  "Say 'oh, don't get me started on that' next time something is mentioned that you have very little interest in talking about",
  "You're a hipster",
  "You're a wizard, Harry",
  "You are yourself from 10 years ago.",
  "You are a sportscaster",
  "You are a feminist",
  "You are an actor who has just won an Academy Award™ and despite knowing that this was likely to happen, you are frazzled and clearly aren’t prepared to be talking",
  "You are an alien who is pretending to be you",
  "You are obsessed with your high school glory days",
  "You are a DJ in the middle of an EDM set",
  "You are the person you fear other people think that you are",
  "You are Joe Exotic",
  "You are incredibly arrogant but are trying your best to seem modest.",
  "You are Troy Bolton. You're heads in the game but you're hearts in the song.",
  "You are a knight who has just slayed a dragon and saved a princess, but upon turning home the princess has immediately gone back to their ex and all the commoners are claiming that the dragon was overhyped to begin with",
  "You are the person who is speaking right NOW",
  "You are yourself from 10 years in the future",
  "You are Billie Eilish",
  "You are the wingman/hypeman/side-kick of another person in the chat. Pick whoever",
  "You are a slam-poet",
  "You are the therapist of the person talking right now",
  "You are a presidential candidate who has been campaigning so long that they cannot stop talking as if they are in the middle of a stump speech",
  "You are controlled by two people with remote controls, but now they're fighting over what to do with you",
  "You are a school-teacher",
  "You are a youth-pastor",
  "You are an Instagram influencer",
  "You enjoy three things: Bears. Beets. Battlestar Galactica",
  "You are the mediocre lead-singer of a struggling emo-pop band",
  "You are your favorite prompt of whatever you've had before. If this is your first prompt, just be yourself",
  "You are your sibling. If you are an only child, just be yourself",
  "You write for Pitchfork",
  "You are a ghost",
  "You are in love with the person talking",
  "You are a statue that has just recently come to life",
  "You are your favorite high school teacher",
  "You are Father John Misty",
  "Grab some water",
  "You are a chess grandmaster still thinking about possible moves you could’ve made in your last game",
  "You are Canadian",
  "You are Dave Chappelle's Tyrone Biggums character from The Chappelle Show. He was a crackhead.",
  "You are Elon Musk",
  "You are speed-dating, and you have a speed-date with everyone in the chatroom. They are unaware of this.",
  "You and the tallest person in the chat are planning to kill the shortest person in the chat",
  "You are a Tom Hardy character. Pick your favorite",
  "You've just become aware of your own mortality for the first time",
  "You are the manager of a professional baseball team. You enjoy chewing gum, being old, and looking bored.",
  "You are slowly realizing that the tallest person in the group chat is your long-last half-sibling",
  "You are a genie",
  "You are hiding something",
  "You are Squidward. You don’t have to do his voice but just, like, react to things the way he would",
  "You are not like other girls",
  "You are very skeptical of anything anyone says",
  "You are a film enthusiast who uses the term ‘visual storytelling’ to sound smart",
  "You are Debbie Downer",
  "You are a wealthy celebrity who says things like ‘Do you know who I am?’",
  "You are a character from BoJack Horseman",
  "You are an NPR radio host. Introduce yourself by name, talk really softly and play some really funky transition music",
  "You are blue collar worker with a thick New York accent",
  "You are 71 years old. Be a little bit too close to your webcam, and when you talk, speak a little bit too loudly",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
];
//This one is for families
export const Family = [
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Talk about a memory you've had with a family member",
  "Make a remark to or about whoever you would consider the 'black sheep' of the family",
  "If your family was a Medievil house and had a slogan ie 'A Lannister Always Pays Their Debts' what would yours be? Decide and then say it naturally in conversation",
  "Say 'You know what we should do' followed by something that you have no interest in doing",
  "Address the naturally coolest person in the family",
  "Address the richest person in the family",
  "Address the elephant in the room",
  "Grab some water",
  "You haven't been listening! Ask a question that has already been answered",
  "Jokingly bring up the worst genetic trait of the family (obesity, depression, etc.)",
  "Reminise fondly about a memory that never happened",
  "Reminise fondly about your least favorite family gathering",
  "Ask about the ex-partner of the person who has gone through a breakup most recently",
  "You are the most culturally aware member of the family! Bring up something and say you read about it in the New Yorker",
  "Drop an F-bomb",
  "Make a political statement that you know would piss of a member of your family",
  "Make a religious statement that you know would piss off a member of your family",
  "Make a political statement that you know would make your family proud, but one that you don't believe",
  "Make a religious statement that you know would make your family proud, but one that you don't believe",
  "Address a member of the family with 'Hey, I heard you did' followed by something that is not true of that person, but is true of another member of the family",
  "Talk about something really interesting that you've been doing recently, but that is not true at all",
  "Lie as many times as possible in the next minute",
  "Pretend to doze off",
  "Address the person who has changed the most since high school",
  "Address the member of the family that is most likely to get in a fist-fight",
  "Start and argument with the person talking right now",
  "Talk about how great your kid is. If you don't have a kid, talk about a dog, a roommate, or a fantasy football team",
  "Bring in the person in the conversation that has been the quietest",
  "Ask someone a question to someone about something that they would feel mildly uncomfortable talking about",
  "Pretend to be yourself from 10 years ago",
  "Pretend to be someone else in the family. Don't do their voice, just say something that you think they would say",
  "Tell a short but boring and irrelevant story",
];

//This one is for coworkers
export const Office = [
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Adjust your tie really thoroughly, like the way Gus Fring did at the end of Breaking Bad season 4",
  "The next time you speak, use the phrase ‘I’m just thinking of the big picture here’",
  "After your coworker says something, say ‘piggybacking off of what [insert name] said,’ and restate what they said but in your own words",
  "Say something positive about your company",
];

//This one is for very personal stuff
export const Dates = [
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "If you have a dog, lie about having a cat. If you have a cat, lie about having a dog. If you have no pets, lie about having a LOT of pets",
  "Say 'high-five' and make a gesture like you're high-fiving the screen",
  "Talk about how you really like a completely made-up TV show or a made-up band",
  "Compliment the other person. Be sincere",
  "Have a blinking fit, like something is really bothering your eye, but don't mention it. If they mention it, stop doing it",
  "Play with your hair. A lot. More than is natural.",
  "Pretend to get emotional about something that you couldn't care less about",
  "Mention a sibling that you don't have",
  "Laugh hysterically at something that you think is funny but is not thhhhaaaaattt funny",
  "You haven't been paying attention! Ask a question that has already been answered",
  "Pretend to swat a fly",
  "Say, 'I know this is our first time meeting and this will sound weird, but' followed by something that is not at all weird to say on a first date",
  "Pretend to be offended by something and then say 'Haha, I'm not offended by that' or something to that matter",
  "Say something that your favorite television character might say",
  "Give a half-formed, unintelligent, but otherwise innocuous opinion about something",
  "Quote a lyric by your favorite artist but don't say that you're quoting it",
  "Talk about the last book you read. Bonus points if it's a book that in no way makes you sound intelligent about having read",
  "Mention something in your immediate vicinity and then move the camera to show the other person it",
  "Lie about your ethnic background (but keep it to the same race)",
  "If you identify as a man, mention something about Joe Rogan or something you heard on The Joe Rogan Experience. If you identify as a woman, say something abou astrology.",
  "Say 'I'm weirdly good at' *blank*",
  "Lie about your education",
  "Don't blink for as long as possible (or just until the next prompt)",
  "Say something that relates to something that that person said earlier",
  "Mention Kanye West",
  "Mention how you used to play bass in a band",
  "Say something that you heard about on a podcast",
  "Say something about Adam Driver or a movie that Adam Driver has been in. Bonus points if it's Lena Dunham's HBO show Girls",
  "Say 'Hmmm, that's pretty interesting' while furrowing your brow",
  "Say 'I respect that!'",
  "Talk about growing up in a state that you didn't actually grow up in",
  "Mention Harry Potter, and how you really like Harry Potter",
  "Say 'this is an unpopular opinion' followed by something that is in no way an unpopular opinion",
  "Mention a similarity between your date and your plant. You might have to get creative for this one",
  "Say 'I was on the worst video date ever once where' and then mention something from earlier in this current video date, and then laugh. This is always a good joke. You're welcome.",
  "Mention the wildly popular alcoholic beverage known as White Claw",
  "Say a terrible joke. Say 'thanks for laughing at that', if they laugh at it",
  "Do some humblebragging. You deserve it",
  "Mention Donald Trump",
  "Say 'How do you feel about' something. This is actually just good conversation advice that you should use even when unprompted",
  "Make a remark that is so self-depracating and cuts so deep that it kind of hurts to say",
  "Next time you talk, use a heavy accent on one word. Try not to be offensive and use an accent that could possibly come from someone of your race",
];

//This one is for first dates
export const Personal = [
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Mention something about the last relationship you've been in",
];
//This one is for first dates
export const Greek = [
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "Just be yourself :)",
  "You are the god/goddess of the last thing you googled",
  "Try to use the word 'tragic' next time you speak",
  "Mention something about the last relationship you've been in",
  "Anger the Titans! Criticize someone in a position of power",
  "Be very emotional about something",
  "Steal some fire from the Gods and give it to man. Say something that you're probably not supposed to",
  "Open Pandora's Box on the conversation by saying something controversial that you will immediately regret saying",
  "Be very happy for the next 30 seconds and then incredibly sad for the 30 seconds that follow that (Your daughter really had to eat those seeds, didn't she)",
  "You are a Minotaur",
  "Next time you say something smart or funny, add something else that makes it less smart or less funny and come crashing down to Earth",
  "You are King Aegeus! Jump to a really bad and incorrect conclusion about something someone said!",
  "You got this, Perseus! While contributing to the conversation, don't look at the camera or at anyone else. Bonus points if you look at someone through a phone camera or cup or something.",
  "Fall madly in love with the next person you address to the point where you have difficulty completing your thought",
  "Say something negative about your father or nice about your mother. Afterwards, close your eyes for a bit",
  "You are an incredibly talented musician, but have lots of doubts about things",
  "Try to do 12 very small things before getting the next prompt, Herculeus",
  "You are a cloud of mist",
  "Give a compliment to the person in the group that you think likes you least, Apollo. Bonus points if that compliment could also apply to a tree",
  "You're getting a little cocky there, Arachne. Call out someone in something that they are better than you at",
  "Echo what someone said",
  "You are in love with yourself",
  "Bring up an animal and talk about how great it is, Bellerophone",
  "Next time someone is being criticized or attacked unfairly in the conversation, come out of the sky and defend them, Perseus!",
  "You are Zeus, King of the Gods",
  "Ok Sisyphus, start an argument or say an opinion that you've said before, but you know will never convince anyone else",
  "Everything you touches turns to gold. You can take this literally or metaphorically",
  "Mention your home, Odysseus, and something that you miss about it",
  "You are half-God, half man",
  "Ok Hera, be really jealous of someone. Bonus points if it's of someone in the chat who recently bore the children of your husband.",
  "You are a tree. You can talk I guess, but you're a tree",
  "Everyone in the group chat is madly in love with you. At least you think so",
  "Next time you address the person with the longest hair, turn to stone the moment you look at them",
  "You are Hermes, the messenger god, and the guider of souls. You're also a bit of a trickster",
  "You are the Muse known as Calliope, and are reknown for your epic poetry and beauty in song. Say something super eloquent or drop some poetry",
  "You are Dionysus, god of parties, drunkeness, and other less important things. Have fun :)",
  "Drag someone to the Underworld by saying an opinion you don't believe and try really hard to get just one person to agree",
  "Ok Pygmalion, mention something cool that you've made",
  "Hi Io. You had Zeus's children, so you are now a cow. You can talk if you want, but you have to moo as well",
  "You are one of the Danaides. Say something negative about men.",
  "You are a tree",
  "You are Athena, goddess of wisdom. Say something wise",
];
