export const Topics = [
  "You are preparing for a picnic",
  "You are at the wedding of Player 1s daughter. Everyone is trying to convince him that the person who is going to marry the daughter is a baaaaad man",
  "You are all planning the perfect crime",
  "You are all in an MUN conference. One of you is the chair.",
  "Player 1 is suing player 2 for defamation",
  "You are all watching a baseball game today",
  "You are all competing in a cooking contest",
  "Player 2 got an awful hair cut. Roast him for it",
  "You are filming a movie. Player 2 is the director, player 3 is the lead actor",
  "You are on a boat in the midle of the ocean with these people",
  "You are on the Titanic. It is starting to sink, but no one has realized it yet. You hear some commotion, but are just kind of annoyed by it. You don't really care what's causing it",
  "You are on a roadtrip. Player 2 is a hostage",
  "Children in the town you live in keep mysteriously disappearing?",
];
